### ISSUE TITLE
회원가입 기능 구현 

### ISSUE THREAD

**Issue by 0han7** [not-easy-news-feed/news-feed-backend#16]
### 회원가입 

> [POST] /api/members/signup
* 로그인 아이디가 존재 할 경우 예외가 발생한다.
* 아이디, 비밀번호를 입력하지 않을 경우 예외가 발생한다.
* 입력된 이메일은 유효한 이메일 형식이어야 한다.

**예외 처리**
- **이름이 비어있는 경우**  
  - **예외 발생**: 클라이언트가 필수 입력값을 누락하거나 유효성 조건을 충족하지 않을 때  
  - **응답**: `400 Bad Request`  
  - **메시지**: `"이름, 이메일, 비밀번호는 필수 입력값입니다."`
- **이메일 형식으로 작성하지 않은  경우**  
  - **예외 발생**: 이메일 입력값을 누락하거나 이메일 형식 조건을 충족하지 않을 경우
  - **응답**: `400 Bad Request`  
  - **메시지**: `"올바르지 않는 이메일 형식입니다."`

### RequestBody
```json
{
   "name"  : "example",
   "password" : "password123",
   "email" : "email@example.com"
}
```

### ResponseBody
```json
{
   "memberId" : 1, 
   "name"  : "example",
   "password" : "password123",
   "email" : "email@example.com",
   "createAt" : "2024-10-21 17:30:31",
   "updateAt" : "2024-10-21 17:30:31"
}
```

**Comment by loadkrnis** [comment]
[POST] /api/members

username -> name

```java
Member member = new Member();

member.getUsername()
member.getName() // O
```

**Comment by loadkrnis** [comment]
응답에    "password"  빠져야함
